name: model
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pypardiso
  - matplotlib
  - pandas
  - numba
  - tqdm
  - h5py
  - jupyter
  - scikit-learn
  - pytest
  - seaborn
  - pyvista
  - scipy
  - networkx
  - notebook
  - ipykernel
  - autograd
  - conda-forge::coolprop
